import type { Tenant } from '@/lib/models/tenant';

/**
 * Fields a caller supplies. `id` is missing on purpose: ids are generated by
 * the store on write, once, and never recomputed from other fields
 * (docs/sheet-schema.md rule 3). A caller that could pass one would sooner or
 * later derive it from a name.
 *
 * `archived` is missing for the same class of reason — it is changed through
 * `archiveTenant`, not by writing a field, so "archive" cannot happen by
 * accident as part of an unrelated edit.
 */
export type TenantDraft = Omit<Tenant, 'id' | 'archived'>;

export interface TenantRepository {
  /** Excludes archived tenants. */
  listTenants(): Promise<Tenant[]>;
  /** Returns an archived tenant too — an old link should show the record, not 404. */
  getTenant(id: string): Promise<Tenant | null>;

  createTenant(draft: TenantDraft): Promise<Tenant>;
  /**
   * Applies only the fields given, leaving the rest as they are. The store
   * still writes the whole record, so re-applying the same update is a no-op
   * rather than a second change — see docs/data-layer.md §4.
   */
  updateTenant(id: string, changes: Partial<TenantDraft>): Promise<Tenant>;
  archiveTenant(id: string): Promise<Tenant>;
}
